version: '3'
services:
  api_service:
    container_name: api_container
    image: api_image
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.api.local
    ports:
      - 5000:5000
    depends_on:
      - db_service

  db_service:
    container_name: db_container
    image: postgres:13.3
    env_file:
      - .env.db.local
    ports:
      - 8000:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data/

  cron_service:
    container_name: cron_container
    image: cron_image
    build:
      context: ./services/cron
      dockerfile: Dockerfile
    env_file:
      - .env.cron.local
    volumes:
      - ./services/cron/cron_tasks/daily:/etc/periodic/daily/:ro
      - ./services/database/backups:/var/backups/postgres
      - ./services/cron/logs:/var/log/
    depends_on:
      - db_service

  nginx_service:
    container_name: nginx_container
    image: nginx:1.25.1-alpine
    volumes:
      - ./services/server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - api_service
volumes:
  postgresql_data: