version: '3'
services:
  api_service:
    container_name: api_container
    image: api_image
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.api.local
    ports:
      - 5000:5000
    depends_on:
      - db_service

  db_service:
    container_name: db_container
    image: postgres:13.3
    env_file:
      - .env.db.local
    ports:
      - 8000:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data/

  nginx_service:
    container_name: nginx_container
    image: nginx_image
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - api_service
volumes:
  postgresql_data: